### ISSUE TITLE
Enable passing of credentials via command line flags

### ISSUE THREAD

**Issue by smithjw** [sebsto/xcodeinstall#26]
**Is your feature request related to a problem? Please describe.**
I would like to run `xcodeinstall` on a GitHub Actions hosted Runner.

**Describe the solution you'd like**
Enable the passing of credentials in either ENV variables or via command line flags rather than an interactive prompt. I could then store the username and password in GitHub Secrets reducing the reliance on passing the creds via an interactive script wrapper or storing them in AWS.

**Additional context**
I'm not looking to use xcodeinstall to install Xcode but instead download the xip, then upload that xip to a management server for distribution out to my engineer's devices from our management system (Jamf Pro)

**Comment by sebsto** [comment]
Hello @smithjw 
Passing security credentials on the command line is deemed insecured. Anybody connected to the machine can issue a `ps ax` command and see the credentials in clear text.
An alternative would be to consome credentials from a text file or a secure credentials store instead.

Have you consider using the `-s` option that allows to securely store the credentials on AWS Secrets Manager ?

**Comment by sebsto** [comment]
will not implement for security reasons
